### ISSUE TITLE
Power Consumption Changes 1.5/2.0

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#131]
It appears from #130 that Thruster power consumption has changed. Further confirmation and data needed.

**Comment by cmmcleod** [comment]
Verified that thruster power consumption has not changed.

**Comment by Shardinara** [comment]
Hiya i was wondering if you had any idea whats happening in that cobra i showed you I still cant account for the 0.54mw difference?

**Comment by cmmcleod** [comment]
Not yet. I checked thruster power consumption and could not find any discrepancy between in-game and the data Coriolis uses. If you have the time could you look at each module in the outfitting screen (in-game) and paste those details here?

I'm going to try to replicate your Cobra build later today to find the source if the issue.

**Comment by Shardinara** [comment]
Thanks for your response, the problem was gone as soon as i upgraded the thrusters to D class now the game and Coriolis are back in step.  I'm puzzled as to what caused it maybe a game bug? i was going to ask if you had the Cr could you just do the same cobra and see what happens. i am restricted what i can check in-game i have about 500k total to my name.

I love this program i find it completely indispensable in game thank you again for creating this.

**Comment by cmmcleod** [comment]
Ah ha! Figured it out!

There was a typo in the Coriolis 4E Thruster power consumption: it is 3.28 not 3.82..

Will fix!

**Comment by Shardinara** [comment]
Mystery solved, Very well done.
