### ISSUE TITLE
Damage / DPS total (for all weapons)

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#6]
Add Damage and DPS to comparisons.

Need to think about how best to model this.

Simplest thing would be to show a sums of dps and damage.

**Comment by danielbarla** [comment]
I believe the best info for *shield damage* at the moment is [this post](https://forums.frontier.co.uk/showthread.php?t=140240) for the actual damage and energy use stats.  Someone made it into a spreadsheet ([reddit post here](http://www.reddit.com/r/EliteDangerous/comments/34b55j/weapon_damage_over_time_graph/)), which basically can predict when your capacitor will be drained for X number of each weapon type, and thus graphs the resulting damage over time.

I believe the damage after capacitor is drained is just ([Capacitor Recharge] / [Total EPS]) * [DPS].  Pips linearly modulate this number, apparently. 

I've made a spreadsheet (Excel, unfortunately) which is a bit more useful, in that it can work out combinations of different weapons (types, modes, classes).  It's quite nice, though some things are missing - e.g. I'm not taking into account different firing groups, etc.  I'm not sure it's worthwhile to show anything at that level, but what I'm saying is that it still doesn't quite reflect reality.

For a simplified display, "time to capacitor drained" could be shown with different pip settings.  Damage at specific intervals (say, 10 seconds, 20 seconds) could be shown.

Of course, we don't really know how hull damage and subsystem damage work at the moment, so that's still missing.

**Comment by danielbarla** [comment]
More info / equations:

Each power distributor has two numbers related to weapons; the total charge ("total charge", expressed in MJ), and how quickly this charge replenishes ("max recharge rate" in MJ/s).  

If we put "pips" number of pips into weapons, the equation for how much energy is charged back into the distributor each second is just:

[actual recharge rate] = ([pips] / 4) * [max recharge rate]

If we have the sum of the energy expenditure ("total EPS") for all weapons being fired, we can work out the actual rate at which the capacitor is being drained ("actual drainage rate"):

[actual drainage rate] = [actual recharge rate] - [total EPS]

From here, we can then work out the "seconds to capacitor drained" figure:

[seconds to capacitor drained] = [total charge] / [actual drainage rate]

In my experience, common pip settings are 0, 2 and 4, giving quite different outcomes.  2 is for a "4 pips to shields" setup, and 4 is generally an all-out attacking one.  0 just for completeness.


If we have the damage per second ("total DPS") of the weapons summed, we can also work out how much damage they would do under capacitor drained conditions ("DPS when drained").  This turns out to be proportional to the ratio of [actual recharge rate] to [total EPS].

[DPS when drained] = ([actual recharge rate] / [total EPS]) * [total DPS]

Of course, in the rare case that our recharge rate exceeds the EPS, we should limit this number to 1.  


If we're given a time period in seconds [total time], over which we want to calculate total cumulative damage, we need to split the time period into two ("time spent before capacitor drained" and "time spent after capacitor drained").

[time spent before capacitor drained] = MIN([total time], [seconds to capacitor drained])

[time spent after capacitor drained] = MAX(0, [total time] - [seconds to capacitor drained])

Cumulative damage over the total period ("cumulative damage") is thus:

[cumulative damage] = ([time spent before capacitor drained] * [total DPS]) + ([time spent after capacitor drained] * [DPS when drained])

**Comment by danielbarla** [comment]
Here's an example of the stats for a dummy Anaconda, and what a graph might look like:

![example stats and graph](https://cloud.githubusercontent.com/assets/12608979/7811452/0e7b14e0-03ab-11e5-9cbe-0dc9ae346359.PNG)

As you can see, the graph is pretty basic, and not particularly interesting.  In general, this is the shape of graph that you can expect, unless you being in firing groups or comparison overlays with other ships.

**Comment by spullara** [comment]
I have an open pull request with the data.

**Comment by iaingalloway** [comment]
Was this implemented? Currently only the module 1-10 ratings for DPS appear to be displayed, and I don't see any way to model capacitor draw.

**Comment by colin-air** [comment]
Yes it was, however data was not available for all weapons. For example pulse lasers have the DPS in MJ listed (e.g.  2E/F DPS: 3 (4MJ)

Missiles and Torpedos do not have any data.

I believe that a lot of this data will change with 2.1 and will require significant in-game testing to gather the data.

**Comment by spullara** [comment]
2.1 seems to have a bunch of the information in game now, though we will
probably still have to vet it.
