### ISSUE TITLE
Finding some missing components with API

### ISSUE THREAD

**Issue by AnthorNet** [cmmcleod/coriolis#95]
Hi,
I was testing the return from EDMarketConnector for outfitting and found that some components were returned but not present in Coriolis.

FSD 8B, 8C for example, do you know if it's missing or an error from the API?

http://ed-td.space/en/29/Outfitting
Here you'll find them, all the unknown except for the hardpoints I haven't finished where not found in coriolis files.

**Comment by cmmcleod** [comment]
The following components almost certainly exist in-game however no ship can mount them (currently): 

 - Life Support - `Class 7, 8`
 - Frame Shift Drive - `Class 7, 8`
 - Thrusters - `Class 8`
 - Sensors - `Class 7`

I imagine the `Federal Corvette`, `Imperial Cutter` `Panther Clipper` will use these. If I can gather data on them before hand I will certainly add them. All components' data are largely gathered from screenshots, etc, which is why you are only seeing them through EDMarketConnector.

Fuel Tank - `Class 7, 8` - These can be found [here](https://github.com/cmmcleod/coriolis/blob/master/data/components/internal/internal_fuel_tank.json)

Right now Fuel Tanks 7+8 can only be mounted by the `Anaconda` or `Type-9`. But again, I imagine the larger newer ships might be able to mount them in the standard slot.

**Comment by AnthorNet** [comment]
Right the fuel tank clearly a false positive as my parser was using that [file](https://github.com/cmmcleod/coriolis/blob/master/data/components/common/fuel_tank.json)

I think I'll assume that API stuff not in Coriolis should not be seen publicly for now :)
